#!/bin/bash

function monitor_settings() {
    sleep .5
    monitor_status=$(xrandr | grep "HDMI-1-4 connected" | wc -l)

    if [ $monitor_status == 1 ];
    then
        # xrandr --auto
        # xrandr --output eDP-1 --off
	xrandr --output eDP-1-1 --auto --output HDMI-0 --auto --left-of eDP-1-1
    fi
}

function caps_to_esc(){ xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'; }

function start() {
    killall $1
    sleep .5
    $($1 $2) &
}

# monitor_settings
caps_to_esc

start nitrogen "--restore"
start picom ""
start spotifyd ""
start rclone "mount remote:/sync /home/jakub/Sync"
start emacs "--daemon"
xinput set-prop 11 344 1
