#!/bin/sh

if [ -n "$1" ]; then
    sudo -E guix system -L $1 reconfigure \
	 -e '((@@ (jd utils) current-operating-system))'
else
    sudo -E guix system reconfigure \
	 -e '((@@ (jd utils) current-operating-system))'
fi;

